use std::iter::once;
use crate::{QuintEx, QuintName};
use crate::utils::QuintIdGenerator;
use crate::lexer::{Token, LexicalError};

grammar(id: &mut QuintIdGenerator);

// Expressions with proper precedence based on Quint.g4
// Precedence levels are from lowest to highest, where 1 is the lowest.
// This flow is different than antlr's format where the highest is the 
// first in the alternatives.
// 
// 1. Braces/Paren
// 2. LetIn
// 3. IfElse
// 4. List
// 5. Record
// 6. Pair
// 7. Unit e.g. "()"
// 8. Tuple
// 9. Literals (int, bool, str) and Identifier
// 10. actionAny
// 11. actionAll
// 12. match
// 13. implies
// 14. iff (equivalence)
// 15. or (disjunction),  or {}
// 16. and (conjunction), and {}
// 17. prime assigment
// 18. relations (==, !=, <, <=, >, >=, ...)
// 19. addition/subtraction (+, -)
// 20. multiplication/division/modulo (*, /, %)
// 21. unary (-)
// 22. power (^)
// 23. list index: hello[1]
// 24. operApp: normalCallname(args?)
// 25. lambda
// 26. dotcall: expr . name (args?)?
pub Expression: QuintEx = {
    Pair,
    Tuple,
    Record,
    ConditionalExp,
}


ConditionalExp: QuintEx = {
    "if" <a:LogicalExp> <b:AtomExp> "else" <c:AtomExp> => {
        QuintEx::QuintApp{
            id:id.get(), 
            opcode: "ite".into(),
            args: vec![a,b,c],
        }
    },
    LogicalExp,
}

LogicalOps: QuintName = {
    "and" => "and".into(),
    "or" => "or".into(),
    "implies" => "implies".into(),
    "iff" => "iff".into()
}
LogicalExp: QuintEx = {
    <lhs:Expression> <opcode: LogicalOps> <rhs:RelationshipExp> => {
        QuintEx::QuintApp{
            id:id.get(), 
            opcode,
            args: vec![lhs, rhs],
        }
    },
    "and" "{" <args:CommaOne<RelationshipExp>> "}" => {
        QuintEx::QuintApp{
            id:id.get(), 
            opcode: "and".into(), 
            args,
        }
    },
    "or" "{" <args:CommaOne<RelationshipExp>> "}" => {
        QuintEx::QuintApp{
            id:id.get(), 
            opcode: "or".into(), 
            args,
        }
    },
    "all" "{" <args:CommaOne<RelationshipExp>> "}" => {
        QuintEx::QuintApp{
            id:id.get(), 
            opcode: "actionAll".into(), 
            args,
        }
    },
    "any" "{" <args:CommaOne<RelationshipExp>> "}" => {
        QuintEx::QuintApp{
            id:id.get(), 
            opcode: "actionAny".into(), 
            args,
        }
    },
    RelationshipExp,
    //PrimeExp,
}

// Prime Assignment
// TODO: this will have an opcode of 'assign' and 2 args. 
// See: line 508 in evaluator.  assumes the lhs was declared earlier
//PrimeExp: QuintEx = {
//    <lhs: Identifier> "'" "=" <rhs:RelationshipExp> => {
//        QuintEx::QuintApp{
//            id:id.get(), 
//            opcode: "assign".into(), 
//            args: vec![QuintEx::QuintStr{id: id.get(), value: lhs}, rhs],
//        }
//    },
//    RelationshipExp,
//}

// Relations
RelationshipOps: QuintName = {
    ">" => "igt".into(),
    ">=" => "igte".into(),
    "<" => "ilt".into(),
    "<=" => "ilte".into(),
    "!=" => "neq".into(),
    "==" => "eq".into(),
}
RelationshipExp: QuintEx = {
    <lhs:RelationshipExp> <opcode: RelationshipOps> <rhs:ArithmeticExp> => {
        QuintEx::QuintApp{
            id:id.get(), 
            opcode, 
            args: vec![lhs, rhs],
        }
    },
    ArithmeticExp,
}

ArithmeticOps: QuintName = {
    "+" => "iadd".into(),
    "-" => "isub".into(),
}
ArithmeticExp: QuintEx = {
    <lhs:ArithmeticExp> <opcode: ArithmeticOps> <rhs:MulDivModExp> => {
        QuintEx::QuintApp{
            id:id.get(), 
            opcode, 
            args: vec![lhs, rhs],
        }
    },
    MulDivModExp,
}

MulDivModOps: QuintName = {
    "*" => "imul".into(),
    "/" => "idiv".into(),
    "%" => "imod".into(),
}
MulDivModExp: QuintEx = {
    <lhs:MulDivModExp> <opcode: MulDivModOps> <rhs:AtomExp> => {
        QuintEx::QuintApp{
            id:id.get(), 
            opcode, 
            args: vec![lhs, rhs],
        }
    },
    UminusExp,
}

UminusExp: QuintEx = {
    "-" <rhs:UminusExp> => {
        QuintEx::QuintApp{
            id:id.get(), 
            opcode: "iuminus".into(), 
            args:  vec![rhs],
        }
    },
    PowExp,
}

// right associative
PowExp: QuintEx = {
    <lhs:AtomExp> "^" <rhs:UminusExp> => {
        QuintEx::QuintApp{
            id:id.get(), 
            opcode: "ipow".into(), 
            args:  vec![lhs, rhs],
        }
    },
    //OperApp,
    ListAccess,
}

// [1,2,3][1], List(1,3)[1]
ListAccess: QuintEx = {
    <n:OperApp> "[" <idx: NumberLiteral> "]" => {
        QuintEx::QuintApp{
            id: id.get(), 
            opcode: "nth".into(), 
            args: vec![n, idx],
        }
    },
    OperApp,
}

CallName: QuintName = {
    LogicalOps,
    Identifier,
}
// OperApp
OperApp: QuintEx = {
    <n: CallName> "(" <args:Comma<Expression>> ")" => {
        QuintEx::QuintApp{
            id:id.get(), 
            opcode: n, 
            args,
        } 
    },
    DotCall,
}

// Lambda

// Dot Call
DotCall: QuintEx = {
    <n:OperApp> "." <opcode: CallName> "(" <mut args:Comma<Expression>> ")" => {
        let mut v = vec![n];
        v.append(&mut args);
        QuintEx::QuintApp{
            id: id.get(), 
            opcode, 
            args: v,
        }
    },
    List,
    AtomExp,
}

// Change to Atom?
AtomExp: QuintEx = {
    NumberLiteral, 
    StrLiteral,
    BooleanLiteral,
    Groupings,
    // Tuple 'uint'
    "("")" => {
        QuintEx::QuintApp{
            id:id.get(), 
            opcode: "Tup".into(),
            args: vec![]
        }
    },
}

Groupings: QuintEx = {
    "{" <Expression> "}" => <>,
    "(" <Expression> ")" => <>,
}

/** Literals **/

Pair: QuintEx = {
    <lhs: AtomExp> "->" <rhs:AtomExp> => {
        QuintEx::QuintApp{
            id:id.get(), 
            opcode: "Tup".into(),
            args: vec![lhs,rhs]
        }
    },
}

// Tuple
TupleItem: QuintEx = {
    "." "_" <value: NumberLiteral> => <>
}

Tuple: QuintEx = {
    "(" <args: CommaTwo<Expression>> ")" => {
        QuintEx::QuintApp{
            id:id.get(), 
            opcode: "Tup".into(),
            args,
        }
    },
    // With item
    "(" <args: CommaTwo<Expression>> ")" <idx: TupleItem> => {
        //args.push(idx);
        let a = QuintEx::QuintApp{
            id:id.get(), 
            opcode: "Tup".into(),
            args,
        };
        QuintEx::QuintApp{
            id:id.get(), 
            opcode: "item".into(),
            args: vec![a, idx]
        }
    },
}

// Literal List 
List: QuintEx = {
    "[" <args:Comma<Expression>> "]" => {
        QuintEx::QuintApp{
            id:id.get(), 
            opcode: "List".into(), 
            args,
        }
    },
}

RecordKeyValue: (QuintEx, QuintEx) = {
    <lhs:Identifier> ":" <rhs:Expression> ","? => {
        (QuintEx::QuintStr{id: id.get(), value: lhs}, rhs)
    },
}

Record: QuintEx = {
    "{" <a:RecordKeyValue*> "}" => {
        QuintEx::QuintApp {
            id:id.get(), 
            opcode: "Rec".into(),
            args: a.iter()
            .flat_map(|tup| once(tup.0.clone()).chain(once(tup.1.clone())))
            .collect::<Vec<_>>(),
        }
    },

    "{" <a:RecordKeyValue*> "}" "." <b: Identifier> => {
        let rec = QuintEx::QuintApp {
            id:id.get(), 
            opcode: "Rec".into(),
            args: a.iter()
            .flat_map(|tup| once(tup.0.clone()).chain(once(tup.1.clone())))
            .collect::<Vec<_>>(),
        };
        QuintEx::QuintApp {
           id:id.get(), 
            opcode: "field".into(),
            args: vec![rec, QuintEx::QuintStr{id: id.get(), value: b}]
        }
    },

    "{" <a:RecordKeyValue*> "}" "." <n: CallName> "("")" => {
        let rec = QuintEx::QuintApp {
            id:id.get(), 
            opcode: "Rec".into(),
            args: a.iter()
            .flat_map(|tup| once(tup.0.clone()).chain(once(tup.1.clone())))
            .collect::<Vec<_>>(),
        };
        QuintEx::QuintApp {
           id:id.get(), 
            opcode: n.into(),
            args: vec![rec]
        }
    },
}

/** qualId, etc... */
Identifier: QuintName = {
    <name:LowId> => name.into(),
    <name:CapId> => name.into(),
    "Set" => "Set".into(),
    "List" => "List".into(),
    "from" => "from".into(),
    "as" => "as".into(),
}

NumberLiteral: QuintEx = {
    <value:Int> => QuintEx::QuintInt{id: id.get(), value},
    <value:Hex> => QuintEx::QuintInt{id: id.get(), value},
}

StrLiteral: QuintEx = {
    <value:String> => QuintEx::QuintStr{id: id.get(), value: value.into()}
}

BooleanLiteral: QuintEx = {
    <value:Bool> => QuintEx::QuintBool{id: id.get(), value}
}

/** Macros **/
#[inline]
Comma<T>: Vec<T> = {
    => Vec::new(),
    CommaOne<T> => <>,
};
CommaOne<T>: Vec<T> = {
    <e:T> <v:("," <T>)*> => {
        let mut v = v;
        v.insert(0, e);
        v
    }
};
CommaTwo<T>: Vec<T> = {
    <e:T> <v:("," <T>)+> => {
        let mut v = v;
        v.insert(0, e);
        v
    }
};

/** Lexer mapping **/
extern {
  type Location = usize;
  type Error = LexicalError;

  enum Token {
    Int => Token::Int(<i64>),
    Hex => Token::Hex(<i64>),
    Bool => Token::Bool(<bool>),
    CapId => Token::CapId(<String>),
    LowId => Token::LowId(<String>),
    String => Token::String(<String>),

    "+" => Token::Add,
    "-" => Token::Sub,
    "*" => Token::Mul,
    "/" => Token::Div,
    "%" => Token::Mod,

    "=" => Token::Assign,
    "==" => Token::EQ,
    "!=" => Token::NE,
    ">" => Token::GT,
    "<" => Token::LT,
    ">=" => Token::GE,
    "<=" => Token::LE,

    "," => Token::Comma,
    ":" => Token::Colon,
    ";" => Token::SemiColon,
    "::" => Token::DoubleColon,
    "." => Token::Period,
    "'" => Token::Prime,
    "|" => Token::Pipe,
    "->" => Token::Arrow,
    "=>" => Token::DoubleArrow,
    "^" => Token::Hat,
    "_" => Token::Underscore,
    "..." => Token::Ellipsis,

    "(" => Token::LParen,
    ")" => Token::RParen,
    "{" => Token::LBrace,
    "}" => Token::RBrace,
    "[" => Token::LBracket,
    "]" => Token::RBracket,

    "module" => Token::Module,
    "const" => Token::Const,
    "assume" => Token::Assume,
    "var" => Token::Var,
    "val" => Token::Val,
    "def" => Token::Def,
    "pure" => Token::Pure,
    "action" => Token::Action,
    "temporal" => Token::Temporal,
    "nondet" => Token::Nondet,
    "run" => Token::Run,

    "all" => Token::All,
    "any" => Token::Any,
    "all" => Token::All,
    "if" => Token::If,
    "iff" => Token::Iff,
    "else" => Token::Else,
    "and" => Token::And,
    "or" => Token::Or,
    "implies" => Token::Implies,
    "match" => Token::Match,

    "Set" => Token::Set,
    "List" => Token::List,

    "import" => Token::Import,
    "export" => Token::Export,

    "as" => Token::As,
    "from" => Token::From,

    "type" => Token::Type,
    "str" => Token::TypeStr,
    "int" => Token::TypeInt,
    "bool" => Token::TypeBool,

    "/*" => Token::Comment,
  }
}
